spring:
  application:
    name: prizeBot
  datasource:
    url: jdbc:postgresql://localhost:5432/prize_bot
    username: root
    password: toor
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

